### ISSUE TITLE
感谢分享,已更新两个小功能

### ISSUE THREAD

**Issue by GuLiSir** [BlueCitizens/bilibili-app-cache-converter#2]
感谢分享. 省了我好多时间. 有个小优化我已经fork并且修改了一下.可以去我主页取
1. 输出路径有些非法路径的字符需要去除
2. 分p的视频放在同一个子目录感觉更合理

**Comment by BlueCitizens** [comment]
谢谢你的优化，最近有些忙一直没有回复，我会抽空检查与合并这些修改
