### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nkh0472** [BlueCitizens/bilibili-app-cache-converter#7]
In readme.md

> 博客
> [将你用手机缓存的B站视频转换为mp4和ass弹幕](https://blog.bckun.top/posts/%E5%B0%86%E4%BD%A0%E7%94%A8%E6%89%8B%E6%9C%BA%E7%BC%93%E5%AD%98%E7%9A%84B%E7%AB%99%E8%A7%86%E9%A2%91%E8%BD%AC%E6%8D%A2%E4%B8%BAmp4%E5%92%8Cass%E5%BC%B9%E5%B9%95.html)

**Comment by BlueCitizens** [comment]
感谢提醒！ ac85dc1fab3bd130948fc8fb27a1a64b6f32f074
